### ISSUE TITLE
Manual Testing: Console Errors

### ISSUE THREAD

**Issue by pkmgarcia** [raghavgupta96/stayinn#103]
# Console Outputs
### **LoginForm Warnings**
**Steps to reproduce: click on login button from homepage**
- [ ] Warning: React does not recognize the `floatingLabelText` prop on a DOM element. (Check TextInput.jsx: 7)
- [ ] Warning: React does not recognize the `errorText` prop on a DOM element. (Check TextInput.jsx: 7)
- [ ] Warning: React does not recognize the `hintText` prop on a DOM element. (Check PasswordInput.jsx: 7)
UI ___________________________
- [ ] navbar does not fully cover the top on the mobile size.
- [ ]  Login form does not stay in the center on the mobile phone screen.
Steps to reproduce: Start App

### **RegisterForm Warnings**
**Steps to reproduce: click on Signup from homepage**
- [ ] Warning: React does not recognize the `floatingLabelText` prop on a DOM element. (Check RegisterForm.jsx: 112)
- [ ] Warning: React does not recognize the `errorText` prop on a DOM element. (Check RegisterForm.jsx: 112)
- [ ] Warning: React does not recognize the `hintText` prop on a DOM element. (Check RegisterForm.jsx: 126)

### **HomePage Warnings**
**Steps to reproduce: click on StayInn on navbar**
- [ ] Warning: Failed prop type: The property `xs` of `Grid` must be used on `item` (Check SearchBox.jsx: 124)
- [ ] Warning: `value` prop on `input` should not be null. Consider using an empty string to clear the component or `undefined` for uncontrolled components. (Check SearchBox: 177)
- [ ] Warning: Each child in an array or iterator should have a unique "key" prop. (Check SearchResult.jsx: 6)

### **Payment Warnings**
**Steps to reproduce: Input '/payment/' after localhost**
- [ ] Warning: Failed prop type: Invalid prop `children` supplied to `Select`, expected a ReactNode. ( Check PaymentForm.jsx: 113)
- [ ] Warning: Failed prop type: Invalid prop `children` supplied to `SelectInput`, expected a ReactNode. (Check PaymentForm.jsx: 113)
- [ ] Warning: Warning: Failed prop type: The prop `value` is marked as required in `SelectInput`, but its value is `undefined`. (CheckForm.jsx: 113)
## Not Used
- [ ] 'SearchBox' is defined but never used  no-unused-vars. (App.js:11)
- [ ]  'SearchBox' is defined but never used no-unused-vars. (App.js:11)
- [ ]  webpackHotDevClient.js:138 ./src/features/auth/register/RegisterForm.jsx
  Line 1:   'Component' is defined but never used       no-unused-vars
  Line 2:   'FormControl' is defined but never used     no-unused-vars
  Line 3:   'Input' is defined but never used           no-unused-vars
  Line 4:   'InputAdornment' is defined but never used  no-unused-vars
  Line 5:   'AccountCircle' is defined but never used   no-unused-vars
  Line 11:  'TextInput' is defined but never used       no-unused-vars
- [ ]  ./src/features/auth/login/LoginForm.jsx
  Line 1:  'Component' is defined but never used  no-unused-vars
- [ ]  ./src/features/nav/navbar/NavBar.jsx
  Line 25:  'profile' is assigned a value but never used  no-unused-vars
- [ ]  ./src/features/payment/form/PaymentForm.jsx
  Line 8:  'connect' is defined but never used  
  Line 9:  'firestoreConnect' is defined but never used

**Comment by yunjunma** [comment]
Payment Testing:
1. Payment page looks like connected to firebase, information flashed and showed invalid information in the trip component after payment page loaded.
